### PR TITLE
Install the package.xml for use by overlay workspaces

### PR DESCRIPTION
**Pull request by cottsay**
CI build: [Build Status](http://build.ros2.org/view/Cci/job/Cci__overlay_ubuntu_bionic_amd64/27/)

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The patch is certainly good as is.

Can you clarify why you need it to be installed? I would expect that there will always be packages which don't install their manifest (or even don't have one in the first place) and we have to handle those cases anyway.

**Comment by cottsay** [comment]
Of course.

The reason that I'd like the `package.xml` installed is that given an archive that I intend to use to build an overlay workspace, I need to enumerate what rosdeps are needed to support the packages in that archive.

Right now, we often get pretty lucky in situations where two or more packages share a rosdep dependency and only some of them install their manifest. If we start using only a subset of the archive, however, I'm discovering many situations where we no longer need the other packages, and due to the missing manifest, we end up missing rosdeps that would have been installed had we invoked rosdep on the source directory instead of discovering the packages in the install directory.

Right now, I believe that this package as well as `urdfdom`, `urdfdom_headers` and `tinyxml_vendor` are the only packages I need to install their manifests in order to reach parity with my hacky solution which abuses colcon-based package discovery.

**Comment by dirk-thomas** [comment]
How will this work for a package like `FastRTPS` which doesn't have a manifest file?

**Comment by cottsay** [comment]
Since Fast-RTPS doesn't have a `package.xml` to begin with, I added its (two) dependencies to the install list unconditionally.

I have no doubt that the number of packages in that list will grow, but installing the package manifests is a more correct solution that also solves the problem in *some* cases.

**Review by dirk-thomas — APPROVED** [review]

**Review by nuclearsandwich — APPROVED** [review]

**Pull request merged**
