### PR TITLE
add package.xml for poco_vendor

### PR DESCRIPTION
**Pull request by mikaelarguedas**
As we have control over this repository I figured it would be better to have the package.xml leaving alongthe code rather than a patch on the release repository.

@nuclearsandwich I removed 2 dependencies that didn't appread to be necessary on my bionic machine
https://github.com/ros2-gbp/poco_vendor-release/blob/7c74e1bfa5d5596fa957817c06cca3ee3b19862c/xenial/package.xml#L14-L15
I tested it by ensuring that these 2 packages were not present and building up to the "composition" package and ran the test of "composition" successfully (couldnt test it on CI as these deps are brought in transitively by other packages like opencv or python3-dev).

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4560/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1470/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3745/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4640/)

### CODE REVIEW

**Review by wjwwood — APPROVED** [review]
format 3? Otherwise lgtm.

**Comment by mikaelarguedas** [comment]
> format 3?

Oh do we have a preference for format 3 ?

I usually use format 3 only when I need format 3 features, but am totally fine changing it to format 3 if it's preferred

**Comment by wjwwood** [comment]
Dunno, I always use format 3 in ROS 2. No reason, just using the latest and greatest.

**Comment by mikaelarguedas** [comment]
> Dunno, I always use format 3 in ROS 2. No reason, just using the latest and greatest.

Fine by me https://github.com/ros2/poco_vendor/pull/15/commits/49e4ab01cf503e4c91210725fdd102f1cff47c83

**Pull request merged**
